// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk-b5tkrmnfAsUJufayis4aDkZDbYzPoM',
    appId: '1:63295472311:web:561b5cb6752c5f5b6fc332',
    messagingSenderId: '63295472311',
    projectId: 'advmobprog-firebase-2add1',
    authDomain: 'advmobprog-firebase-2add1.firebaseapp.com',
    storageBucket: 'advmobprog-firebase-2add1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHhWm0rKdSvuf4QG8YO3IXwXQlmiq18FA',
    appId: '1:63295472311:android:9b02cc7672914e4a6fc332',
    messagingSenderId: '63295472311',
    projectId: 'advmobprog-firebase-2add1',
    storageBucket: 'advmobprog-firebase-2add1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_rcKh-0op7Q1x8WLNLOXV6t9j_N9-n-U',
    appId: '1:63295472311:ios:15459c9b2652b5e06fc332',
    messagingSenderId: '63295472311',
    projectId: 'advmobprog-firebase-2add1',
    storageBucket: 'advmobprog-firebase-2add1.firebasestorage.app',
    iosBundleId: 'com.example.alegreMobile',
  );
}
